services:
  postgres:
    container_name: postgres-2e280af9eba28241
    build:
      context: ..
      dockerfile: docker/Dockerfile.postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 7777:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data
      - ./db-init-scripts:/docker-entrypoint-initdb.d

volumes:
  postgres-volume:
    driver: local
